name: "Pages"

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
  repository_dispatch:
    types:
      - webhook
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Generate Files"
        run: |
          node gen-files.js

      - name: "Configure Pages"
        uses: actions/configure-pages@v5

      - name: "Jekyll Build Pages"
        uses: actions/jekyll-build-pages@v1
        with:
          source: "./src"

      - name: "Upload Pages Artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Deploy Pages"
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages

  stack:
    name: "Update Stack"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: deploy

    steps:
      - name: "Portainer Deploy"
        uses: cssnr/portainer-stack-deploy-action@v1
        with:
          token: ${{ secrets.PORTAINER_TOKEN }}
          url: ${{ secrets.PORTAINER_URL }}
          name: flask-random-image
          file: docker-compose-swarm.yaml
          repo: https://github.com/smashedr/flask-random-image
          ref: refs/heads/master
